languageCode = "en"
languageName = "English"
weight = 1
title = "ake blog"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = ""
  description = "My personal thoughts & ideas."
  # ... otras configuraciones ...
  showHeaderSearch = false     # Esto quita la lupa de búsqueda
  showAppearanceSwitcher = false # Esto quita la pieza mecánica (cambiador de tema)
  
  [params.footer]
  # ... otras configuraciones ...
  showPoweredBy = false        # Esto elimina el texto "Powered by Hugo & Blowfish"
  showDonationButton = false   # Esto elimina el icono de la taza de café/donación

  [params.author]
  name = "ake"
  email = "-.-"
  image = ""
  headline = "My personal thoughts & ideas."
  bio = "Just a normal dude..."
  links = []  # Esto deja la lista vacía de forma limpia y profesional