languageCode = "es"
languageName = "Español"
weight = 2
title = "ake blog"

[params]
  displayName = "Español"
  isoCode = "es"
  dateFormat = "2 de enero de 2006"
  description = "Mis pensamientos e ideas personales."
  
  [params.author]
    name = "ake"
    headline = "Mis pensamientos e ideas personales."
    bio = "Solo un tipo normal..."
    links = []