baseURL = "https://akemarropa.github.io/blog/"
theme = "blowfish"
title = "ake blog"

languageCode = "en"
defaultContentLanguage = "en"

# --- CONFIGURACIÓN ANTIFALLOS ---
relativeURLs = false
canonifyURLs = false

disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[taxonomies]
  tag = ""
  category = ""

[permalinks]
  posts = "/posts/:slug/"

[params]
  colorScheme = "blowfish"
  defaultAppearance = "dark"