baseURL = "https://akemarropa.github.io/blog/"
publishDir = "docs"
theme = "blowfish"

defaultContentLanguage = "en"
disableLanguages = ["es"]

[params]
  colorScheme = "blowfish"
  defaultAppearance = "dark"
  # Mantenemos la rueda
  showAppearanceToggle = true
  # Quitamos la lupa
  enableSearch = false

  # ESTA ES LA SECCIÓN CRÍTICA
  [params.footer]
    showPoweredBy = false
    showHugoGenerator = false
    showCopyright = true

[params.homepage]
  showRecent = true
  showRecentItems = 10
  layout = "background"