baseURL = "https://akemarropa.github.io/blog/"
theme = "blowfish"
title = "ake blog"
languageCode = "en"

# --- CONFIGURACIÓN PARA GITHUB PAGES ---
canonifyURLs = true
relativeURLs = false

# Esto evita que Hugo se confunda con las carpetas
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[permalinks]
  posts = "/posts/:slug/"

[params]
  colorScheme = "blowfish"
  defaultAppearance = "dark"