backend:
  name: github
  repo: akemarropa/blog
  branch: main

# Media and Public folders
media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - label: "Category"
        name: "categories"
        widget: "select"
        options: ["Art", "Tech", "AI", "General"]
        required: false  # Esto permite no poner nada
        multiple: false
      - {label: "Tags", name: "tags", widget: "list", default: ["blog"]}
      - label: "Body"
        name: "body"
        widget: "markdown"
        buttons: ["bold", "italic", "link", "heading-two", "heading-three", "quote", "bulleted-list", "numbered-list", "image"]