backend:
  name: github
  repo: akemarropa/blog # Tu usuario y repositorio
  branch: main

publish_mode: editorial_workflow # Esto te permite guardar borradores
media_folder: "static/images" # Donde se guardarán las fotos
public_folder: "/images"

collections:
  - name: "posts"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Borrador", name: "draft", widget: "boolean", default: false}
      - {label: "Cuerpo", name: "body", widget: "markdown"}