name: Autodeploy Hugo

on:
  push:
    branches:
      - main  # Se activa cuando guardas algo en el CMS o haces push

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          rm -rf public docs
          hugo --minify
          mkdir docs
          cp -r public/. docs/
          touch docs/.nojekyll

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "Robot: Web actualizada automáticamente" || echo "No hay cambios para subir"
          git push origin main